imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    secret: ThisTokenIsNotSoSecretChangeIt
    locale_fallback: en
    ezpublish_legacy.default.view_default_layout: eZDemoBundle::pagelayout.html.twig
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user:
    mailer_password:
    
framework:
    esi:             { enabled: true }
    fragments:       ~
    translator:      { fallback: %locale_fallback% }
    # The secret parameter is used to generate CSRF tokens
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection:
        enabled: true
        # Note: changing this will break legacy extensions that rely on the default name to alter AJAX requests
        # See https://jira.ez.no/browse/EZP-20783
        field_name: ezxform_token
    validation:      { enable_annotations: true }
    # Place "eztpl" engine first intentionnally.
    # This is to avoid template name parsing with Twig engine, refusing specific characters
    # which are valid with legacy tpl files.
    templating:      { engines: ['eztpl', 'twig'] } #assets_version: SomeVersionScheme
    trusted_proxies: ~
    trusted_hosts: []
    session:
        save_path: "%kernel.root_dir%/sessions"
        # The session name defined here will be overridden by the one defined in your ezpublish.yml, for your siteaccess.
        # Defaut session name is "eZSESSID{siteaccess_hash}" (unique session name per siteaccess).
        # See ezpublish.yml.example for an example on how to configure this.
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ eZDemoBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

ez_publish_legacy:
    enabled: true
    root_dir: %kernel.root_dir%/../ezpublish_legacy

# Caching
fos_http_cache:
    cache_control:
        defaults:
            overwrite: false
        rules:
            - match:
                    path: ^/
                headers:
                    cache_control: { public: true, max_age: 3600, s_maxage: 3600 }
