#!/bin/sh

VERSION="5.4"

set -e
set -x

if [ ! -d ./web ]; then
  mkdir ./web
fi
cat <<EOL > ./web/.htaccess
RewriteEngine On
RewriteRule .* error.php?error=503
EOL

cat <<EOL > ./web/error.php
<?php
if ( !isset( \$_GET['error'] ) ){ \$_GET['error'] = 503; }
header('HTTP/1.1 '.\$_GET['error'].' Service Temporarily Unavailable');
header('Retry-After: 600');
echo \$_GET['error'] . " Building try later.";
exit();
EOL

wget -O ezpublish5.tar.gz --no-check-certificate "http://packages.xrow.com/software/5.4/ezpublish5-5.4.0-ee-bul-full.tar.gz"
tar --strip-components=1 -xzf ezpublish5.tar.gz
rm -Rf ezpublish5.tar.gz

sed -i "s/CURLOPT_CONNECTTIMEOUT, 3/CURLOPT_CONNECTTIMEOUT, 10/g" ezpublish_legacy/kernel/setup/steps/ezstep_site_types.php
sed -i "s/\/\/umask(/umask(/g" ezpublish/console
sed -i '/<?php/ a\
umask(0000);' web/index.php

sed -i "/^\[RepositorySettings\]/,/^\[/ {
        s|^RemotePackagesIndexURL[[:blank:]]*=.*|RemotePackagesIndexURL=http:\/\/packages.ez.no\/ezpublish\/5.4\/5.4.0\/|
}" ezpublish_legacy/settings/package.ini

find {ezpublish/{cache,logs,config,sessions},ezpublish_legacy/{design,extension,settings,var},web} -type d | xargs chmod -R 777
find {ezpublish/{cache,logs,config,sessions},ezpublish_legacy/{design,extension,settings,var},web} -type f | xargs chmod -R 666

cat <<EOL > ./auth.json
{
    "http-basic": {
        "updates.ez.no": {
            "username": "${INSTALLATION_ID}",
            "password": "${LICENCE_KEY}"
        }
    }
}
EOL

rm -f composer.json
wget --no-check-certificate -O composer.json https://raw.githubusercontent.com/xrowgmbh/xrowvagrant-demodata/ez-sylius/composer.json

php /var/www/sites/composer.phar -n update

chmod 755 ezpublish/console

ezpublish/console -n assets:install --symlink --relative web
ezpublish/console -n ezpublish:legacy:assets_install --symlink --relative web
# ether
#ezpublish/console -n assetic:dump --env=prod
# or
ezpublish/console -n assetic:dump --env=dev
composer -n dump-autoload --optimize

# get demodata
if [ ! ${DATABASE_PASSWORD} ]; then
    mysqlauth=" -h ${DATABASE_SERVER} -u ${DATABASE_USER}"
else
    mysqlauth=" -h ${DATABASE_SERVER} -u ${DATABASE_USER} -p${DATABASE_PASSWORD}"
fi
rm -Rf ezpublish_legacy/settings/override ezpublish_legacy/settings/siteaccess ezpublish_legacy/var/ezdemo_site/log ezpublish_legacy/var/ezdemo_site/cache
wget --no-check-certificate -O dump.zip https://github.com/xrowgmbh/xrowvagrant-demodata/archive/ez-sylius.zip
unzip -o -d . dump.zip
cp -r xrowvagrant-demodata-ez-sylius/* .
rm -Rf xrowvagrant-demodata-ez-sylius
rm -Rf ezpublish_legacy/var/ezdemo_site/log/ ezpublish_legacy/var/ezdemo_site/cache/
mysql ${mysqlauth} -e"CREATE DATABASE IF NOT EXISTS ${DATABASE_NAME}"
mysql ${mysqlauth} ${DATABASE_NAME} < ezpublish_legacy/var/ezdemo_site/dump.sql
rm -Rf dump.zip

cd ezpublish_legacy && php bin/php/ezpgenerateautoloads.php && cd ..
source /usr/share/ezcluster/bin/tools/fixpermissions.sh
# Bug https://project.issues.ez.no/IssueView.php?Id=12514&activeItem=1
echo "For solr indexing run:"
echo "php ezpublish/console ezpublish:legacy:script --env=dev -n extension/ezfind/bin/php/updatesearchindexsolr.php"

# set the right database
sed -i "s/database.host: localhost/database.host: ${DATABASE_SERVER}/g" ezpublish/config/parameters.yml
sed -i "s/database.name: ezpublish/database.name: ${DATABASE_NAME}/g" ezpublish/config/parameters.yml
sed -i "s/database.user: root/database.user: ${DATABASE_USER}/g" ezpublish/config/parameters.yml
sed -i "s/database.password: publish/database.password: ${DATABASE_PASSWORD}/g" ezpublish/config/parameters.yml

sed -i "s/Server=localhost/Server=${DATABASE_SERVER}/g" ezpublish_legacy/settings/siteaccess/ezdemo_site_admin/site.ini.append.php
sed -i "s/User=root/User=${DATABASE_USER}/g" ezpublish_legacy/settings/siteaccess/ezdemo_site_admin/site.ini.append.php
sed -i "s/Password=/Password=${DATABASE_PASSWORD}/g" ezpublish_legacy/settings/siteaccess/ezdemo_site_admin/site.ini.append.php
sed -i "s/Database=ezpublish/Database=${DATABASE_NAME}/g" ezpublish_legacy/settings/siteaccess/ezdemo_site_admin/site.ini.append.php

sed -i "s/Server=localhost/Server=${DATABASE_SERVER}/g" ezpublish_legacy/settings/siteaccess/ger/site.ini.append.php
sed -i "s/User=root/User=${DATABASE_USER}/g" ezpublish_legacy/settings/siteaccess/ger/site.ini.append.php
sed -i "s/Password=/Password=${DATABASE_PASSWORD}/g" ezpublish_legacy/settings/siteaccess/ger/site.ini.append.php
sed -i "s/Database=ezpublish/Database=${DATABASE_NAME}/g" ezpublish_legacy/settings/siteaccess/ger/site.ini.append.php

wget --no-check-certificate -O web/robots.txt https://raw.github.com/xrowgmbh/xrowvagrant/master/ezcluster/templates/robots.txt
wget --no-check-certificate -O web/.htaccess https://raw.github.com/xrowgmbh/xrowvagrant/master/ezcluster/templates/.htaccess

rm -Rf ezpublish_legacy/var/cache/*
rm -Rf ezpublish/cache/*
rm -Rf ezpublish_legacy/var/ezdemo_site/cache/*
rm -Rf ezpublish_legacy/var/storage/packages/*
rm -Rf ezpublish_legacy/settings/override/*.php~
rm -Rf ezpublish_legacy/settings/siteaccess/*/*.php~
rm -Rf web/var/cache/*
ezpublish/console cache:clear

echo "Done completely"
