#!/usr/bin/env sh

SCRIPT=`basename $0`
rm -Rf $SCRIPT
COMPOSER_NO_INTERACTION=1
mkdir tmp
composer create-project --no-dev ezsystems/ezplatform tmp dev-master
mv tmp/* .
rm -Rf tmp/
php ezpublish/console ezplatform:install demo
